apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: deployment-manager
data:
  ASPNETCORE_URLS: http://+:8080
  Database__Host: "mssql.deployment-manager.svc.cluster.local"
  Database__Name: "DeploymentManagerDatabase"
  Database__User: "sa"

# Source: https://kubernetes.io/docs/concepts/configuration/configmap/