flowchart TB
    TUI["Deployment Manager TUI"]
    Agent["Deployment Manager Agent"]

    API["Deployment Manager API"]

    DB[("Deployment Manager Database")]
    GitHub["GitHub Releases"]

    TUI -->|"manage customer deployments"| API
    Agent -->|"request installation package"| API

    API -->|"manage deployment data"| DB
    API -->|"fetch release package"| GitHub